### ISSUE TITLE
www server is not work on Apple M1

### ISSUE THREAD

**Issue by alrex5401** [webpwnized/mutillidae-docker#13]
www server is not work on Apple M1

www              | [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex 
www              | (95)Operation not supported: could not create accept mutex

**Comment by webpwnized** [comment]
Mutillidae uses the Mutex default which intends to allow [the APR system](https://apr.apache.org/) to determine the best setting for Mutex. It sounds like the APR system is either detecting or setting the optimal value. However, it is safe to say that detecting/interrogating the underlying infrastructure and changing the setting is not something the Mutillidae application is well suited for. This should be done by APR. Hopefully, APR will issue an update that allows Apache to detect the M1 chip and make the necessary adjustments to the Mutex.

In the meantime, per [the Apache documents](https://httpd.apache.org/docs/2.4/mod/core.html#mutex), I think you can use [the Apache Mutex directive](https://httpd.apache.org/docs/2.4/mod/core.html#mutex) to change how the Mutex works to suit the Apple M1 chip.  The best setting for Apple M1 is probably "sem" or "posixsem". 

I am hesitant to change the project because I am the only developer on this project (not sure you knew that) and...

1. I do not have an Apple M1 computer to test the impact of the changes on the M1
2. I do not have an array of other computers to be sure that changing for M1 would not impact other users with common systems like Windows, and Linux using Intel processors
3. I do not have a way to regression test the changes across all the users of Mutillidae.
4. Referring to the above explanation, the Apache APR should detect the underlying infrastructure and make this change automatically

If you want to test the manual fix, I think there are two ways. The directive would be added to the end of the Apache configuration file like this:

RUN echo "Mutex posixsem" >> /etc/apache2/apache2.conf

Mutillidae sets the configuration in [the www/Dockerfile](https://github.com/webpwnized/mutillidae-docker/blob/master/www/Dockerfile).

Also, you can change the Apache server being used in [the same Docker file](https://github.com/webpwnized/mutillidae-docker/blob/master/www/Dockerfile). The Apache container used is set at the top of the file about Line 5.
