### ISSUE TITLE
Newest php version is not compatible with Mutillidae

### ISSUE THREAD

**Issue by mhogstrom** [webpwnized/mutillidae-docker#14]
https://php.watch/versions/8.2/dynamic-properties-deprecated

I get php errors when accessing for example WebServices DnsLookup.
The docker files are based on mysql:debian latest, which includes the latest php, which deprecates dynamic properties.

Deprecated: Creation of dynamic property wsdl::$serviceName is deprecated in /var/www/mutillidae/webservices/soap/lib/nusoap.php on line 4718

**Comment by webpwnized** [comment]
Update so far: 

1. Ubuntu (my dev environment) does not have PHP 8.2 yet. I am checking how to install it so I can test it with you. 
2. I checked how many class object references are in NuSoap thinking I might try to fix them manually. There are more than 2,700 so that idea is out the window. 
3. Investigation continues but it looks like either the exact errors are needed, or PHP 8.2 has to be installed to test.

**Comment by webpwnized** [comment]
Patched in version 1.0.41 which itself is patched by version 2.11.5 of Mutillidae
