### ISSUE TITLE
Error with composing

### ISSUE THREAD

**Issue by Funktown027** [webpwnized/mutillidae-docker#15]
docker-compose up
Creating network "mutillidae-dockerhub_datanet" with the default driver
Creating network "mutillidae-dockerhub_ldapnet" with the default driver
Creating volume "mutillidae-dockerhub_ldap_data" with default driver
Creating volume "mutillidae-dockerhub_ldap_config" with default driver
Creating directory ... 
Creating database  ... error

Creating directory ... error
211e8f29b46d1f67a0eeeef1800380ca5cd". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for directory  Cannot create container for service directory: Conflict. The container name "/directory" is already in use by container "cfb4e4ae223d66524c4fe13d0b2c0d624b8e43f403c7fb190db16e04dcd0f055". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for database  Cannot create container for service database: Conflict. The container name "/database" is already in use by container "c511d89c38b2ff494cd16c207113d211e8f29b46d1f67a0eeeef1800380ca5cd". You have to remove (or rename) that container to be able to reuse that name.

ERROR: for directory  Cannot create container for service directory: Conflict. The container name "/directory" is already in use by container "cfb4e4ae223d66524c4fe13d0b2c0d624b8e43f403c7fb190db16e04dcd0f055". You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

**Comment by webpwnized** [comment]
The container name is already in use by another container, so Docker is not able to start the new container unless you first stop the existing container that has that same name. You may want to purge existing containers to get a fresh start. This video explains. 

_**[Docker: How to Delete all Images and Containers](https://www.youtube.com/watch?v=VaFGnn6Y4wI)**_

Depending on how new containers are, you can also use search engines to search by the Docker error message. Docker is well supported because it is so heavily used. Search engines often reveal others that have had the same issue. 

**_[DuckDuckGo - Already in use by container](https://duckduckgo.com/?q=already+in+use+by+container)_**
