### ISSUE TITLE
fix: build problem with latest tag on database Dockerfile

### ISSUE THREAD

**Issue by SoftwrDev** [webpwnized/mutillidae-docker#6]
I wrote a PR trying to solve this issue and explaining it a little bit more in depth #5

**Comment by webpwnized** [comment]
I changed the tag to "FROM mysql:debian" because other methods caused build issues on Google Cloud Platform (GCP). This seems to give the best balance by avoiding locking into a specific (and probably unpatched) version of MySQL and impact from the MySQL team flipping back and forth between various operating systems.
